isomerpages/psd-psw

- event-details/Learning Journey
---
layout: simple-page
title: Learning Festival 1-19 July 2019
permalink: /events/learning-journeys/event-details/SIMS1
breadcrumb: Learning Festival
---
What's Singapore's Education Story? Visit MOE's Heritage Centre to understand the Singapore Education Story and its role in nation-building. Through a guided tour, participants will visit every zone in the heritage gallery to explore a different era of education in Singapore. 
**Date and Time: 5 Jul 2019, 2.30pm to 4.00pm 
**Location: MOE Heritage Centre, 402 Commonwealth Drive, S(149599) 
**Indicate Your Interest [here](https://www.eventbrite.sg/e/step-into-my-shoes-making-a-difference-as-a-probation-officer-tickets-61082209533)**
> Learning Journey

- _events/0a-LF1(1-6Jul).md
Changed end time from 12pm to 11am
> Updated time for Tiong Bahru LJ

- _pswlf-2020/1e-occ4.md
- _pswlf-2020/1f-occ5.md
- pages/what-is-psw.md
Updated session date and time for "A Product Management Approach to Building Singapore’s National Digital Identity" by Govtech.
> Update session date and time

- _allworkouts-archive/trial_psw.md
- _exclusives-2020/civil-service-club-promotion.md
- _exclusives-2020/clubhouse-promotions-2020.md
- _exclusives-2020/merchant-exclusives.md
- _exclusives-2020/social-activities-2020.md
- _pswlf-2020/1b-occ1.md
- _pswlf-2020/1f-occ5.md
- _pswlf-2020/1g-occ6.md
- _pswlf-2020/1h-occ7.md
> Updated CSC Pages

- _pswlf-2020/1b-occ1.md
- _pswlf-2020/1c-occ2.md
- _pswlf-2020/1d-occ3.md
- _pswlf-2020/1e-occ4.md
- _pswlf-2020/1f-occ5.md
- _pswlf-2020/1g-occ6.md
- _pswlf-2020/1h-occ7.md
- _pswlf-2020/1i-occ8.md
- _pswlf-2020/3b-accounting.md
- _pswlf-2020/3f-regulation.md
- _pswlf-2020/3g-science.md
- _pswlf-2020/4-ppdevelopment.md
Change of PSD sessions for OCC 5 & 7.
> Change of PSD sessions for OCC 5 & 7

- _pswlf-2020/1b-occ1.md
- _pswlf-2020/1d-occ3.md
> Re-add registration links for Health Millionaire

- Events_2021/terms-and-conditions.md
> T&Cs for OPSOC

- _exclusives-2021/cs-club-facilities-chalet-promotions.md
- _exclusives-2021/cs-club-merchant-exclusives.md
Change to links, t&cs and formatting
> Changes to CS Club pages

- _exclusives-2021/cs-club-merchant-exclusives.md
Updating of terms for merchant exclusives
> Updating of terms for Merchant exclusives

- misc/custom.scss
Removing the grey overlay on hero banner
> Update custom.scss (Removing grey overlay on hero banner)

- index.md
Update Hero Section, as at 30 May
> Update Hero Section, as at 30 May

- _pst-awards-covid-2022/PST Awards (COVID).md
- _pst-awards-covid-2022/collection.yml
- _pstc-2022/Calendar of Events and Activities.md
Update PSTAC COVID Microsite (as at 1 June)
> Update PSTAC COVID Microsite (as at 1 June)

- _pst-awards-covid-2022/PST Awards (COVID).md
Update PSTAC-C Page (as at 10 Jun)
> Update PSTAC-C Page (as at 10 Jun)

- _exclusives-2022/Exclusives 2022/Merchant Exclusives.md
- _exclusives-2022/Exclusives 2022/Sports & Family Day.md
> Update CSClub (as at 29 Jun)

- _exclusives-2022/Exclusives 2022/Merchant Exclusives.md
> Update CSClub (as at 1 Jul)

- _exclusives-2022/Exclusives 2022/Civil Service Club Facilities Promotions.md
Hi Both,
Please assist to push live! 
Thank you
> Pull Request

- _exclusives-2022/Exclusives 2022/Sports & Family Day.md
Update Sports & Family Day Poster (as at 20 Jul)
> Update Sports & Family Day Poster (as at 20 Jul)

- _pswspark/Guided Tours.md
> PSW: Spark Guided Tours

- _discovering-goodatwork/About Discovering Good@Work.md
- _discovering-goodatwork/Available Positions.md
- _discovering-goodatwork/Browse Available Positions.md
- _discovering-goodatwork/What Officers Say.md
- _discovering-goodatwork/collection.yml
Edits made to page title, main video shifted to opening page
> Discovering Good@Work Edits 

- _pswspark/About PSW: Spark.md
Update on PSW: Spark Programme and link
> Update on PSW: Spark Programme and link

- _discovering-goodatwork/About Discovering Good@Work.md
- _psw-exclusives/Facilities & Chalet Promotions.md
- _psw-exclusives/Free Online Social Activities.md
Removed "<p></p>" on the last bullet point on the about page.
> Removed Unnecessary Formatting on the About Page

- _exclusives-2024/Deals & Promotions.md
Update of placement text to include merchant names
> Update of deals description

- _exclusives-2024/Deals & Promotions.md
Edited the deal for Omnidesk with code
> Minor edit to deal

- _pstc-2024/About PST Convention.md
- index.md
Updated programme outline in view of updated HCS segment of 40 mins
> Updated Event Timings and Programme Outline
